### PR TITLE
Adjective: Glitchy

### PR DESCRIPTION
**Pull request by rc7s**
test

### CODE REVIEW

**Comment by LadyK** [comment]
These are some nice pieces of code! Please add in comments, as to your thought process and what you are trying to achieve. As to the piece "evolutionary", this is a perfect piece of code to re-structure and organize into functions. You can make one web(), and by passing in different parameters, make a distinct stroke color. Please do this.

I saw Herman Kogan perform at ISEA this summer. Your sketch reminded me of parts of the performance. Have you seen his work?  https://vimeo.com/102158828

Keep the development coming. I looking forward to seeing what you add next. Movement and Interactivity, could be some options.

**Comment by rc7s** [comment]
Thanks! I'll add comments and re-structure my "evolutionary" piece, though I'm going to continue working on the glitchy one as I like it more and am not sure where I could go with the evolutionary piece.

That Herman Kogan performance is nice stuff. I just watched it. I really like Ryoji Ikeda's work (he's the sound artist not sure if he or a team makes the visuals) https://vimeo.com/search?q=ryoji+ikeda . I'd like to somehow implement audio into my sketch so I guess I could check online and try it when I need to.

**Comment by rc7s** [comment]
I'm using text (well just for numbers around the cursor, specifically). It doesn't really mean or hint to anything contextually so would that be alright?

Also I'm using the get() function to capture an image within my program and load it each frame. When you say no pictures would that count?

-Ryan

**Comment by LadyK** [comment]
Hi Ryan, the numbers and image are fine. You aren't loading an image, but capturing an image of the sketch. The numbers are more for visual effect (i'm assuming) rather than data, information or direction. That's all fine. Something to consider is to think about how to change things over time. You have an experience that is not the same moment to moment. But, over a period, it's largely the same. Is it possible to develop another stage? Another thing to consider is sound. Check out the minim library. But craft the use of sound, as you have this code, rather than just a straight forward sounds track. Keep it coming!

**Comment by LadyK** [comment]
Also, I'd like to see you incorporate custom functions that pass parameters, and arrays. :)

**Comment by rc7s** [comment]
Learned a bit of minim. Thanks for sharing that! Also added some custom functions with passed parameters, and a few 'scenes' that trigger by frame count.

**Comment by LadyK** [comment]
Nice job! I like how the piece fluxes. The use of text and sound is nice. Keep up the experimentations!

**Pull request closed without merging**
