### PR TITLE
project 1 update

### PR DESCRIPTION
**Pull request by jht301**
I'm having trouble bringing the jack piece in front of the trampoline.
i also wanted to know if there was a way to limit a translate statement
to only one function. if i were to put jack() after trampoline() in void
draw the jack part would also translate

### CODE REVIEW

**Comment by LadyK** [comment]
Hello,

Yes, you can limit the translate to one statement/function. pushMatrix() and popMatrix() help to restore settings for limitations. Check out the text on this, as well as the tutorials on Processing. ----> https://processing.org/tutorials/transform2d/

Don't forget about order of operation. The order that you type things is the order that they appear. Try switching them around, to see if they resolve the effect that they are after.

Put comments in your code, so I can see what you are trying and your line of thought.

p.s. Super happy to see you active on Github. :+1:

**Comment by LadyK** [comment]
Jack, the project brief specifies to make weekly pushes demonstrated clear progress. I'm a bit concerned. Hopefully, it's just a matter of not having pushed new material up. Check out your classmate's repos to see what kind of progress they are making.

Have you reviewed the texts and on-line tutorials about push & pop?

Some other things to develop/incorporate: mouse control(how long does the mouse have control? When does the mouse no longer have control?), motion, speed, various conditions that happen, etc. This can go much farther.

**Comment by jht301** [comment]
i believe i pushed another update earlier this week i just forgot to submit a pull request. i learned more about push and pop. is it ok that i have the letters in it? i might make the trampoline move with keys and have the jack jump up and down on it.

**Comment by jht301** [comment]
i updated the file. did you get a notification about that? it's not letting me submit another pull request.

**Comment by LadyK** [comment]
This is some great progress! Keep in mind that mousePressed can either be a boolean variable, or a function - mousePressed(){}. In your case, it's more common to see it used as a function. Yet, here you achieve the same effect due to the if statement.

**Pull request closed without merging**
