### PR TITLE
project adj

### PR DESCRIPTION
**Pull request by CathyC21**
I wasn't sure how far I was supposed to go with this progress but I wanted to do something with the adjective elated. When I think of elated, I think of colorful and happy things and for some reason that image is balloons in the sky. As environmentally unfriendly as that is, it gives a feelings of freedom and happiness. 
I'm a bit unsure where I'm planning to go with this image, but I plan to do interactive stuff with the balloons and hopefully other objects i think to add in there. I understand lerpColor now so I think that's progress!

### CODE REVIEW

**Comment by LadyK** [comment]
Hi Catherine, check out Daniel Shiffman's Nature of Code http://natureofcode.com/. I think a great direction for you would be to add physics to get the float and bounce. In order to do that, I would translate my code into vectors, using Processing's PVector class. Look into it and the book.

**Comment by CathyC21** [comment]
The vectors were a bit confusing at first but after reading nature of code, it became easier as I coded more. I'm wondering if there is another possible way to code the vectors so that parameters can be passed through. I'm sure there is but as I was doing this progress, I couldn't figure out how. I think it would be a lot shorter code if it was possible. I've been trying to add new elements such as mousePressed, keyPressed, etc. But as I looked at examples, there's always a value attached to it. Must I do fill(value) for the functions to work or else can I put another function inside fill()? And if I can, how do I declare it so that it is the same as (value == 0)?

**Comment by LadyK** [comment]
Hello! Great to see the addition of vectors here. I can see you've been checking out the Nature of Code! :+1: Classes make the most sense, if you want to organize your code and not type so much. If you are familiar with OOP, give it a go. You'd want to make your balloon a class, passing different parameters to make it (color, size, etc) and different methods (actions -ie movement, etc).

As for mousePressed and keyPressed and attached values, what are you struggling with? Generally they are booleans, which are either true or not true. They can also be functions, so that different things execute when the condition is true. Check out ---> https://processing.org/tutorials/interactivity/

http://lmgtfy.com/?q=Processing+fill() 

With reference to:

"And if I can, how do I declare it so that it is the same as (value == 0)?"

Please add a comment within your code so I can answer this question better. I need a context.

**Comment by CathyC21** [comment]
I added rain because contrast to most people's thoughts I find rain happy :dancer: 
I was able to make it into a class because it was a simple for loop; however I'm having a bit of trouble with the balloons since it has multiple vectors and colors, so I kept it the way it is for now. I am still working on it on another file so hopefully I get it soon. 
I'm a bit unsure what else to add but I think I'm missing some interactivity.

**Comment by CathyC21** [comment]
made the mouse pressed more interesting than just rain. I will be adding in parameters after testing some more stuff out.

**Comment by LadyK** [comment]
Hi Catherine! This is coming along quite nicely. I love seeing the progress and development. Don't forget your class constructors. This is an important element to classes and making a new instance of the class.

Think about motion, time and interactivity. How could what you have chance over time? Different states could be added (just like what you have), with gradations in between. Think about different forces that could effect movement, like gravity, or even a weight dropped into water (vs something not as heavy). Think about how you can keep track of time, even between events, states or user input. Or, working in 3D. :)

**Comment by CathyC21** [comment]
I added the constructors and parameters that I needed. I had trouble with the umbrella stick because it kept being thick and I looked for possible overlaying codes but couldn't find any. I must have forgotten about something or failed to see where it went wrong XD.

**Comment by LadyK** [comment]
Look at the parameters for rect(). It's how you are utilizing the extra parameters. As you program, look for ways to optimize code and condense it. For instance, ball could be a class, just like you did for raindrop. Review the code so that you can better organize it.

Moving forward, I'd like to see how what you code/your projects, change over time. How do they develop/evolve/vary? How does this relate to the users experience?  Think beyond just a couple states. How could your code be generative?

Nice job.

**Pull request closed without merging**
