### PR TITLE
Project Progress

### PR DESCRIPTION
**Pull request by sharonhlee**
So far I've sketched out my object. I'm not completely sure what adjective I will be choosing, but I would obviously like to interact with the puppy in an interesting way. I'm thinking maybe the adjective playful, which I can take in a few different directions. My code for the puppy alone is kind of lengthy. I'm wondering if there is a way to cut it down without losing the detail and look I want the puppy to have. For now, I'm going to go forward in organizing it more by placing lines within individual functions.

### CODE REVIEW

**Comment by LadyK** [comment]
This is great, Sharon! Think about grouping body parts together and adding in variables. This could help to animate different parts for his body and allow for discreet motion. This would be valuable in moving forward. Clever use of the cross hairs to allow for your drawing position!

**Comment by sharonhlee** [comment]
I added a few timed animations to my puppy to make him look less static and more "alive." I'm not sure if I should put the animation code in the draw function or in the individual body part functions. My plan going forward is to make the puppy's body size change as you interact with it (probably centered on some sort of feeding action by the user). I'm going to add variables to the body function to adjust according to certain conditions. 

Still not sure what adjective this describes...

**Comment by sharonhlee** [comment]
So I think I've figured out how to pass variables in the function to adjust the puppy's size based on the action of feeding him. I do think I'm going to set a condition for him to stop taking the treats after a certain size...it's kind of an upsetting image if you keep going and I would like to avoid condoning animal abuse...

**Comment by LadyK** [comment]
Hi Sharon! It's great to see the development here! I agree with the limits on feeding/growing. Perhaps think of other "states" you can give the puppy, in order to convey emotion. Working with time, and user input would help to facilitate this. Getting him to move or jump would be fun to see too.

**Comment by sharonhlee** [comment]
I've added a limit on the feeding/growth, but also allowed a way of jumping so the pup can "exercise" and go back to his original size. I also added some different emotional states as well as a clearer emotional status in a thought bubble. There's also an array measuring how much the puppy trusts the user, in which there are values added to the list the longer/the more you let the puppy get sick.

I also decided my adjective will be responsible, because you can only interact with the puppy by being responsible with how you handle him.

**Comment by LadyK** [comment]
Nice job here! I love the states of the puppy. It's great! What's managing the values in your array? Do they ever change once they are full? Does your array ever get zero'd out? Another things you want to keep an eye on, is variable scope/access. Global variables have their place. Yet when so many functions access and change the same variable, it's wise to pass the value in to a local variable and to have the function return the value to be used elsewhere locally.

**Pull request closed without merging**
