### PR TITLE
working on making letter functions

### PR DESCRIPTION
**Pull request by tamarticus**

### CODE REVIEW

**Comment by LadyK** [comment]
I love your idea and approach. Keep it coming. Get the interactivity in there. Look up mouse and keyboard functions. I'm especially curious to see what you add, to push your idea further.

**Comment by LadyK** [comment]
Hi Tamar! It's good to see your progress here with making this interactive. I know what you showed me in class yesterday was different than the code here. Were you able to implement some of the things we discussed? Also check out this demo ---> https://processing.org/examples/rollover.html

Some other things to think about are motion, and change over time. How would your piece be experienced after ten minutes? Keep it coming!

**Comment by tamarticus** [comment]
I think I uploaded this wrong because there seems to be two files. 
The right one is large_Game_tamar_palgon/large_Game_tamar_palgon.pde

**Comment by tamarticus** [comment]
Also, I ended up changing some things around, and the way it is now the highlight is different so the pmouse thing wasn't necessary in the end.

**Comment by LadyK** [comment]
Wow, lots of changes here! It's good to put comments in your code, even references for your later self. ;) I'm not quite sure how I'm supposed to get points, but we can talk about that later. Moving forward, I'd like to see how you utilize time and changes over time - whether dynamically or algorithmically - as well as custom functions that pass parameters.

It's great to see this project!

**Pull request closed without merging**
