### PR TITLE
Beginning of Project

### PR DESCRIPTION
**Pull request by k8elau**
So far, for my adjective stretchy, I’ve just placed the initial static
shapes and colored them all. By next submission, I hope to figure out
how to know when a mouse position is within the confines of a shape.

### CODE REVIEW

**Comment by LadyK** [comment]
Love love love seeing documentation of your mental process in your code. Keep it up! Have you seen Golan Levin's holiday cards?  http://www.flong.com/projects/newyear/

https://processing.org/examples/rollover.html
https://processing.org/examples/mousefunctions.html

Keep it coming!

**Comment by k8elau** [comment]
I think I accidentally wrote my description in the title, oops. Either way, I rewrote it here for clarity. 
I’ve figured out how to make the program recognize when the mouse is over any of the shapes (the links were very helpful, thanks!). However, I've run into the problem where the top vertex of my triangle will only distort when the mouse is within the triangle. I know this is a logic problem, so I'm trying to figure out what to do to resolve this. The holiday cards were also really awesome :~)

**Comment by LadyK** [comment]
You might need to deal with vertices and beginshape()/ endShape(), in order to pull certain points of the shape out for stretch. But there are many ways to do this. Working with vertices then allows you to control the location of each vertice and the motion (or tweening) between these points. There might be a nice library out there for tweening with Processing or P5.js. Otherwise, I'd look into PVectors and vertices and Daniel Shiffman's Nature of code to get the Physics working.

**Comment by k8elau** [comment]
Thanks! Using beginShape() and endShape() helped a lot. I made arrays to hold the values of x's and y's, so I could easily adjust vertex values. I made a lot of changes, namely because I think I have a better idea of what I want to achieve. I've been playing around with adjusting opacity, but I think instead I'm going to make the colors lighter the more the shape is stretched from original position. I'm going to try to achieve this using the dist(), and maybe map()? Next, the two shapes are going to act differently once they are no longer stretched, My adjectives are still sticky/stretchy, and I think I've achieved the basics of the sticky part, so now I have to work on the stretchy (specifically the ways the shapes bounce back). For the rectangle, I was going to try to make it bounce back like a spring, and I found a couple of reference materials, and Daniel Shiffman's Nature of Code where they use actual physics formulas to simulate it, so I'll have to look more into that. For the triangle, I want the top vertex to "follow" and stretch out to the mouse and stop once it actually reaches the mouse. Then, I want it to gradually retract back to it's original position when the mouse leaves the screen. However, I'm having trouble figuring out how exactly to achieve this. I'm thinking of maybe incrementing/decrementing the vertex coordinates by .1 until it reaches either mouse position or original position, but I don't know how to get it to "stop." I saw another example on Nature of Code where a circle accelerated towards the position of a mouse (http://natureofcode.com/book/chapter-1-vectors/ - algorithm #3) and hovered around the mouse once it got there, so I'm thinking of creating a PVector to represent all the points from the top vertex of the triangle to the mouse. I'll have to look at PVectors some more, though.

**Comment by LadyK** [comment]
You are definitely making progress and this is awesome to see! Your code is much better organized! A few things you might want to look at and/or incorporate:
- Mouse over the shapes to access control of the shape. This or other mouse parameters/variables would help making the interaction cleaner, by allowing user to release on of the shapes, before effecting the other. There is a mouse over example in the Processing examples from the Learning Processing website. 
- calculating the distance that something has moved, and then mapping that to the color, sounds like a plan!
- look more into the Nature of Code to simulate something moving towards the mouse and stopping at it's arrival. Then retracting back to position afterwards. Work on these as discreet steps! First, utilize PVectors in your code. This makes applying physics much easier, even through it takes some time. Check out chapters 1 & 2 in NoC, then chapter 6 for Arrive. :)

**Comment by k8elau** [comment]
I think overall I am mostly happy with how this came out. The image is intended to represent the adjectives sticky and stretchy. I learned lots about using vectors with nature of code, and found it helped tremendously in getting the vertex to follow the mouse and thus get the triangle to stretch. I wanted to add a spring-like motion when retracted,  but I found it confusing referring to http://natureofcode.com/book/chapter-3-oscillation/ because of all the variables and physics involved. Also, I wish I was able to successfully map color changes when the triangle reverts to its own position (inside the file I explain why I was unable to). In the future I hope to get the spring - part implemented as well as redo some of the logic in the triangle mapping.

**Comment by LadyK** [comment]
With regard to:
colorTriChange = constrain(colorTriChange, 0, 82); //prevents triangle from turnign green

---> Watch where you call fill() and when. If you need something to be a certain color, best to fill() right before.

As for the map() issues, best to pull that out and get that going on a basic level. Turn everything else off. Then bring it back in slowly with different control statements. It seems that there are multiple conditions there. Simplify.

Nice job with the motion and classes!

**Pull request closed without merging**
